mask_threshold: 0.5
model_path: 'weights/model.pth'

model_params:
    num_classes: 25
    trainable_backbone_layers: 0
    transform_params:
        min_size: 800
        max_size: 3200
        image_mean: [0.485, 0.456, 0.406]
        image_std: [0.229, 0.224, 0.225]

dataset_params:
    use_aug: False
    shuffle: False
    batch_size: 1
    annotations_folder: 'dataset/val/annotations'
    image_folder: 'dataset/val/images'
